### ISSUE TITLE
Useful enough... Sarcasm

### ISSUE THREAD

**Issue by TheOldRustyCrown** [spinagon/ComfyUI-seamless-tiling#2]
How to install it? :O Because now it really sounds like "Well... Just push LMB on main comifyui folder, then Shift+Delete and just install automatic build, before that moment when your brain explodes"

**Comment by spinagon** [comment]
Generally, to install extension you go to `<ComfyUI_main_dir>/ComfyUI/custom_nodes` and `git clone` the repository there
https://github.com/ltdrdata/ComfyUI-Manager is an extension that has UI to search and manage other extensions
