### ISSUE TITLE
Is there a sample workflow?

### ISSUE THREAD

**Issue by CustodialMatter** [spinagon/ComfyUI-seamless-tiling#9]
I'm sure it's probably easy for ComfyUI veterans, but for me who is learning this right now I'm struggling

I tried dragging the example pic to Comfy and says workflow not found.  Wishful thinking lol

**Comment by razvanab** [comment]
I don't know if this is what you are looking for, but I hope it helps.

[panorama.json](https://github.com/user-attachments/files/17083453/panorama.json)

**Comment by CustodialMatter** [comment]
That was extremely helpful, thank you!  It worked on the first try

Side note, where can I find more reliable workflows like this?  The ones I get from OpenArt and Civitai are usually busted even if I carefully update and gather all components

**Comment by razvanab** [comment]
Here are some other websites where you can get some workflows:
https://comfyworkflows.com/
https://tensor.art/
https://www.runcomfy.com/

**Comment by spinagon** [comment]
Added sample workflow to readme
